[package]
name = "fgbutil"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = { version = "3.1.0", features = ["derive"] }
geozero = { git = "https://github.com/georust/geozero.git", default-features = false }

[dependencies.flatgeobuf]
path = ".."

[workspace]
members = ["."]
